/* 조건에 부합하는 중고거래 댓글 조회하기 Oracle
URL <https://school.programmers.co.kr/learn/courses/30/lessons/164673>
*/

SELECT B.TITLE as TITLE, 
    R.BOARD_ID AS BOARD_ID,
    R.REPLY_ID AS REPLY_ID,
    R.WRITER_ID as WRITER_ID, 
    R.CONTENTS as CONTENTS, 
    TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') as CREATED_DATE
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
WHERE B.BOARD_ID = R.BOARD_ID
AND TO_CHAR(B.CREATED_DATE,'YYYY-MM') = '2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC